# Site settings
name: Slim Bouguerra
description: "Primarily I am Computer Scientist! Depending on the season, either I am a rock climbing fanatic or I am a backcountry skier enthusiast."
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  b-slim
facebook_username: medslim
#vk_username: your_vk_username_goes_here
twitter_username: slimclimb
#google_plus_username: your_google_plus_username_goes_here
linkedin_username: bslim1
#vine_username:  your_vine_username_goes_here
instagram_username:  slimclimb
#flickr_username: your_flickr_username_goes_here
#steam_username: your_steam_username_goes_here
soundcloud_username:  realslim-1
stack_of_username: 5953288
#reddit_username: your_reddit_username_goes_here
#medium_username:  your_medium_username_goes_here
#tumblr_username: your_tumblr_username_goes_here
#weibo_username: your_weibo_username_goes_here
#lastfm_username: your_lastfm_username_goes_here
#blog_url: "/blog"
email: slim.bouguerra@gmail.com
#public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://pbs.twimg.com/profile_images/967926291352641536/p4b3dp0N_400x400.jpg"


front_img: yes
front_img_path: "https://scontent-sjc3-1.xx.fbcdn.net/v/t31.0-8/416583_3108853153748_759639168_o.jpg?_nc_cat=0&oh=2b54941676316ac2970c68d8a6b5bc42&oe=5B6AABEF"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
